# submit description file for testing the java universe:
Universe                = java
 
# executable              = /home/submitter/submit/Spinning/src/us/kbase/SpinningAPI/SpinningAPImainClass.class
executable              = SpinningAPImainClass.class
initialdir              = /home/submitter/submit/Spinning/src        
arguments                = us.kbase.SpinningAPI.SpinningAPImainClass 0 localhost
# log                     = /home/submitter/submit/Spinning/out/logfile.txt
output                  = /home/submitter/submit/Spinning/out/outfile.txt
error                   = /home/submitter/submit/Spinning/out/errors.txt

should_transfer_files   = No 
# when_to_transfer_output = ON_EXIT

periodic_remove = RemoteWallClockTime > 10

queue
