# submit description file for executable job_exec01.sh

executable              = /home/submitter/submit/Spinning/scripts/job_exec01.sh
log                     = /home/submitter/submit/Spinning/out/logfile01.txt
output                  = /home/submitter/submit/Spinning/out/outfile01.txt
error                   = /home/submitter/submit/Spinning/out/errors01.txt
should_transfer_files   = Yes
when_to_transfer_output = ON_EXIT
queue